table dim_data_entrega
	lineageTag: 67919620-f838-4485-ae30-2901e56e7946

	column cod_data_entrega
		dataType: int64
		formatString: 0
		lineageTag: ba9562f2-7ddd-44db-8106-7c0ad29f4cfb
		summarizeBy: none
		sourceColumn: cod_data_entrega

		annotation SummarizationSetBy = Automatic

	column data_entrega
		dataType: dateTime
		formatString: Long Date
		lineageTag: 90a09c94-2ad0-40ec-b66a-34539993306a
		summarizeBy: none
		sourceColumn: data_entrega

		variation Variation
			isDefault
			relationship: 3252a904-dc31-4653-8980-445e1d3446ee
			defaultHierarchy: LocalDateTable_dcfd9323-c532-4adb-aa3f-a0e6d13684b2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_data_entrega = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\CaioAraujo\Downloads\base_processo_seletivo_dataside.xlsx"), null, true),
				    Export_Sheet = Fonte{[Item="Export",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Relatório de vendas", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type text}, {"Column11", type text}, {"Column12", type any}, {"Column13", type text}, {"Column14", type any}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",3),
				    #"Linhas alternadas removidas" = Table.AlternateRows(#"Linhas Superiores Removidas",1,2,2),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Linhas alternadas removidas", [PromoteAllScalars=true]),
				    #"Cabeçalhos Promovidos2" = Table.PromoteHeaders(#"Cabeçalhos Promovidos1", [PromoteAllScalars=true]),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos2",{{"num_venda", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado3",{{"Column2", "data_venda"}, {"Column3", "data_entrega_prevista"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"data_venda", type date}, {"data_entrega_prevista", type date}, {"data_entrega", type date}, {"vendedor_cod", type text}, {"produto_cod", type text}, {"produto_custo_unitario", Currency.Type}, {"qtd_itens", type number}, {"preco_unitario", Currency.Type}, {"valor_bruto", Currency.Type}, {"ocorrencia_devolucao", type text}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado1",{"data_entrega"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Outras Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Duplicatas Removidas" = Table.Distinct(#"Linhas em Branco Removidas"),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Duplicatas Removidas", "Índice", 1, 1, Int64.Type),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Índice Adicionado",{{"Índice", "cod_data_entrega"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas1",{"cod_data_entrega", "data_entrega"})
				in
				    #"Colunas Reordenadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

