table dim_cidade
	lineageTag: 22c79b1c-124d-4cdf-bca3-ad0c5085442f

	column cidade_cod
		dataType: string
		lineageTag: c1677bee-af49-4b8e-8ae1-97fa98a3cf36
		summarizeBy: none
		sourceColumn: cidade_cod

		annotation SummarizationSetBy = Automatic

	column cidade_nom
		dataType: string
		lineageTag: d2ca2201-2fb7-4132-bd53-2a9d98c4b76d
		summarizeBy: none
		sourceColumn: cidade_nom

		annotation SummarizationSetBy = Automatic

	column País = "Brasil"
		lineageTag: 90ca0b8b-aee7-4687-b783-455a1858c00a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_cidade = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\CaioAraujo\Downloads\base_processo_seletivo_dataside.xlsx"), null, true),
				    Export_Sheet = Fonte{[Item="Export",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Relatório de vendas", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type text}, {"Column11", type text}, {"Column12", type any}, {"Column13", type text}, {"Column14", type any}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",3),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas",{"Column12", "Column13"}),
				    #"Linhas Superiores Removidas1" = Table.Skip(#"Outras Colunas Removidas",4),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Linhas Superiores Removidas1", [PromoteAllScalars=true]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Cabeçalhos Promovidos1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"cidade_cod", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado1", {"cidade_cod"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

