table Vendedor
	lineageTag: cc4b76a7-95ef-44a2-a714-5b62e6489fba

	measure '% Meta Alcançada' = ```
			
			IF(
			    ISFILTERED(dim_vendedor[vendedor_nom]) 
			    || ISFILTERED(dim_supervisor[supervisor])
			    || ISFILTERED(dim_vendedor[equipe]),
			    DIVIDE([Faturamento], [Meta por Vendedor]),
			    BLANK()
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 508a69d8-68b9-4bb7-9e24-d2490d7da9ff

	measure 'Resumo Vendedor' =
			
			FORMAT([% Meta Alcançada], "0%") & " atingido"
		lineageTag: eda6221d-58ea-4588-aafc-151f5943f189

	measure '% Meta Alcançada SVG' =
			
			IF(
			    ISFILTERED(dim_vendedor[vendedor_nom])
			    || ISFILTERED(dim_supervisor[supervisor])
			    || ISFILTERED(dim_vendedor[equipe]),
			
			    VAR Meta = [% Meta Alcançada]
			    VAR Width = 200
			    VAR Height = 20
			    VAR Filled = CEILING(Width * Meta, 1)
			    VAR Remaining = Width - Filled
			    VAR Texto = IF(NOT ISBLANK(Meta), FORMAT(Meta, "0%"), "")
			    VAR XTexto = MIN(Filled + Remaining / 2, Width - 10)
			    VAR SVG =
			        "<svg width='" & Width & "' height='" & (Height + 20) & "' xmlns='http://www.w3.org/2000/svg'>"
			        & "<rect x='0' y='20' width='" & Filled & "' height='" & Height & "' fill='#1976D2'/>"
			        & "<rect x='" & Filled & "' y='20' width='" & Remaining & "' height='" & Height & "' fill='#E0E0E0'/>"
			        & "<text x='" & XTexto & "' y='16' font-family='Arial' font-size='12' fill='#222' text-anchor='middle'>" & Texto & "</text>"
			        & "</svg>"
			    RETURN
			        "data:image/svg+xml;utf8," & SVG,
			    BLANK()
			)
		lineageTag: ceeb322d-3e93-41e3-bb0c-e16c70e2d7db

	partition Vendedor = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

