table dim_clientes
	lineageTag: 4608ca4d-2210-4984-b245-786cceeee1e2

	column cliente_cod
		dataType: string
		lineageTag: 082fdbf8-083c-4660-b8d7-717309d29ea3
		summarizeBy: none
		sourceColumn: cliente_cod

		annotation SummarizationSetBy = Automatic

	column cliente_nome
		dataType: string
		lineageTag: 67798962-a736-480c-979f-261c84582930
		summarizeBy: none
		sourceColumn: cliente_nome

		annotation SummarizationSetBy = Automatic

	column cliente_segmento
		dataType: string
		lineageTag: 8feb0ca7-4746-4a1d-8c39-e62e80b72aa8
		summarizeBy: none
		sourceColumn: cliente_segmento

		annotation SummarizationSetBy = Automatic

	partition dim_clientes = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\CaioAraujo\Downloads\base_processo_seletivo_dataside.xlsx"), null, true),
				    Export_Sheet = Fonte{[Item="Export",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Relatório de vendas", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type text}, {"Column11", type text}, {"Column12", type any}, {"Column13", type text}, {"Column14", type any}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",3),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas",{"Column9", "Column10", "Column11"}),
				    #"Linhas Superiores Removidas1" = Table.Skip(#"Outras Colunas Removidas",4),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Linhas Superiores Removidas1", [PromoteAllScalars=true]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Cabeçalhos Promovidos1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"cliente_cod", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado1", {"cliente_cod"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

