table dim_produtos
	lineageTag: 17d41eda-1ad0-45ba-8daa-805fccf5a55e

	column produto_cod
		dataType: string
		lineageTag: 66c5a586-5438-4ee6-8096-ff8d0653c3e0
		summarizeBy: none
		sourceColumn: produto_cod

		annotation SummarizationSetBy = Automatic

	column produto_nome
		dataType: string
		lineageTag: 9a42c81e-9a3f-4885-803d-296a0af2b4ba
		summarizeBy: none
		sourceColumn: produto_nome

		annotation SummarizationSetBy = Automatic

	column produto_grupo
		dataType: string
		lineageTag: b46196bd-45da-4a74-bb35-cfcc2a623461
		summarizeBy: none
		sourceColumn: produto_grupo

		annotation SummarizationSetBy = Automatic

	column produto_linha
		dataType: string
		lineageTag: 9db1ed0c-d2ac-4eec-8412-49719c605354
		summarizeBy: none
		sourceColumn: produto_linha

		annotation SummarizationSetBy = Automatic

	column produto_fornecedor
		dataType: string
		lineageTag: b98cb592-e347-475e-a242-8b7d8dd04cfc
		summarizeBy: none
		sourceColumn: produto_fornecedor

		annotation SummarizationSetBy = Automatic

	partition dim_produtos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\CaioAraujo\Downloads\base_processo_seletivo_dataside.xlsx"), null, true),
				    Export_Sheet = Fonte{[Item="Export",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Relatório de vendas", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type text}, {"Column11", type text}, {"Column12", type any}, {"Column13", type text}, {"Column14", type any}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",3),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas",{"Column14", "Column15", "Column16", "Column17", "Column18"}),
				    #"Linhas Superiores Removidas1" = Table.Skip(#"Outras Colunas Removidas",3),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Linhas Superiores Removidas1", [PromoteAllScalars=true]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Cabeçalhos Promovidos1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"produto_cod", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado1", {"produto_cod"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

